name:                JpegRawOrganizer
version:             1.0.0.0
github:              "githubuser/JpegRawOrganizer"
license:             BSD3
author:              "Andreas Moser, Christoph Sürig"
maintainer:          ""
copyright:           "2017 Andreas Moser, Christoph Sürig"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/JpegRawOrganizer#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- cgi
- split
- text

library:
  source-dirs: src

executables:
  JpegRawOrganizer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JpegRawOrganizer
    - directory
    - filepath
    - cgi
    - split
    - text

tests:
  JpegRawOrganizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JpegRawOrganizer
    - directory
    - filepath
    - cgi
    - split
    - text
    - hspec
    - QuickCheck
